extends:
  - 'universe/native'
  - 'universe/shared/typescript-analysis'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
settings:
  import/resolver:
    typescript:
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.d.ts'
    parserOptions:
      project: './tsconfig.json'
rules:
  lines-between-class-members:
    - warn
    - always
    - exceptAfterSingleLine: true
  spaced-comment: 
    - warn
    - always
